import Article from "./models/article.js";
const articles = [
  {
    title: "What is GMX?",
    body: "body",
    url: "https://academy.binance.com/en/articles/what-is-gmx",
    published_date: null,
    reading_time: 7,
    difficulty: "Indermediate",
    topic: null,
    img: "https://public.bnbstatic.com/static/academy/uploads-original/987db33b05d54cf89289f6e4200a5f20.png",
  },
  {
    title: "What Is WOOFi? ",
    body: "body",
    url: "https://academy.binance.com/en/articles/what-is-woofi",
    published_date: null,
    reading_time: 5,
    difficulty: "Indermediate",
    topic: null,
    img: "https://public.bnbstatic.com/static/academy/uploads-original/cb2f27e8cfc84a4f96b6797d2a3fd50e.png",
  },
  {
    title: "What Are Soulbound Tokens (SBT)? ",
    body: "body",
    url: "https://academy.binance.com/en/articles/what-are-soulbound-tokens-sbt",
    published_date: null,
    reading_time: 5,
    difficulty: "Indermediate",
    topic: null,
    img: "https://public.bnbstatic.com/static/academy/uploads-original/f46be85e6de94c0897ddac34b7576c11.png",
  },
  {
    title: "What Is Kyber Network (KNC)?",
    body: "body",
    url: "https://academy.binance.com/en/articles/what-is-kyber-network-knc",
    published_date: null,
    reading_time: 7,
    difficulty: "Indermediate",
    topic: null,
    img: "https://public.bnbstatic.com/static/academy/uploads-original/19ead76d555a4c95bd8c0faf6d3d77f9.png",
  },
  {
    title: "What Is NEAR Protocol (NEAR)?",
    body: "body",
    url: "https://academy.binance.com/en/articles/what-is-near-protocol-near",
    published_date: null,
    reading_time: 6,
    difficulty: "Indermediate",
    topic: null,
    img: "https://public.bnbstatic.com/static/academy/uploads-original/e196996f8ae34464b849c4b6e0ea9112.png",
  },
  {
    title: "What Are Bitcoin Stamps?",
    body: "body",
    url: "https://academy.binance.com/en/articles/what-are-bitcoin-stamps",
    published_date: null,
    reading_time: 4,
    difficulty: "Indermediate",
    topic: null,
    img: "https://public.bnbstatic.com/static/academy/uploads-original/2bf62cad40bf423a836419fa5e413dc9.jpg",
  },
  {
    title: "What Are Bitcoin Layer 2 Networks?",
    body: "body",
    url: "https://academy.binance.com/en/articles/what-are-bitcoin-layer-2-networks",
    published_date: null,
    reading_time: 6,
    difficulty: "Indermediate",
    topic: null,
    img: "https://public.bnbstatic.com/static/academy/uploads-original/d89287b55eaa461b97bb6cd27b37f822.jpg",
  },
  {
    title: "What Is the Solana Virtual Machine (SVM)?",
    body: "body",
    url: "https://academy.binance.com/en/articles/what-is-the-solana-virtual-machine-svm",
    published_date: null,
    reading_time: 6,
    difficulty: "Indermediate",
    topic: null,
    img: "https://public.bnbstatic.com/static/academy/uploads-original/f32cf2ef3d384f79b287777e08039475.jpg",
  },
  {
    title: "What Is Tether (USDT)?",
    body: "body",
    url: "https://academy.binance.com/en/articles/what-is-tether-usdt",
    published_date: null,
    reading_time: 8,
    difficulty: "Beginner",
    topic: null,
    img: "https://public.bnbstatic.com/static/academy/uploads-original/2fd4345d8c3a46278941afd9ab7ad225.png",
  },
  {
    title: "How to Analyze DeFi Projects",
    body: "body",
    url: "https://academy.binance.com/en/articles/how-to-analyze-defi-projects",
    published_date: null,
    reading_time: 10,
    difficulty: "Beginner",
    topic: null,
    img: "https://public.bnbstatic.com/static/academy/uploads-original/1fa81414b4ce4bdba7ec8fc3421b5dcf.png",
  },
  {
    title: "What Is Layer 1 in Blockchain?",
    body: "body",
    url: "https://academy.binance.com/en/articles/what-is-layer-1-in-blockchain",
    published_date: null,
    reading_time: 10,
    difficulty: "Beginner",
    topic: null,
    img: "https://public.bnbstatic.com/static/academy/uploads-original/1b51e2748ea74f71ae52ebe1ab34d962.png",
  },
  {
    title: "Crypto Payments Explained",
    body: "body",
    url: "https://academy.binance.com/en/articles/crypto-payments-explained",
    published_date: null,
    reading_time: 7,
    difficulty: "Beginner",
    topic: null,
    img: "https://public.bnbstatic.com/static/academy/uploads-original/787aafb4ecd641269fce3661d9226c04.png",
  },
  {
    title: "What Are Pre-Markets?",
    body: "body",
    url: "https://academy.binance.com/en/articles/what-are-pre-markets",
    published_date: null,
    reading_time: 5,
    difficulty: "Beginner",
    topic: null,
    img: "https://public.bnbstatic.com/static/academy/uploads-original/c0c27898189b441cb3d8c6aabf592c42.png",
  },
  {
    title: "What Are Index Funds?",
    body: "body",
    url: "https://academy.binance.com/en/articles/what-are-index-funds",
    published_date: null,
    reading_time: 5,
    difficulty: "Beginner",
    topic: null,
    img: "https://public.bnbstatic.com/static/academy/uploads-original/6c927e025c9d41feb03236dfe2b4c32c.png",
  },
  {
    title: "5 Tips to Secure Your Cryptocurrency Holdings",
    body: "body",
    url: "https://academy.binance.com/en/articles/5-tips-to-secure-your-cryptocurrency-holdings",
    published_date: null,
    reading_time: 4,
    difficulty: "Beginner",
    topic: null,
    img: "https://public.bnbstatic.com/static/academy/uploads-original/439a04f7835b4ab281c0fa6b3bfc8f5b.png",
  },
  {
    title: "What Is Real Yield in DeFi?",
    body: "body",
    url: "https://academy.binance.com/en/articles/what-is-real-yield-in-defi",
    published_date: null,
    reading_time: 6,
    difficulty: "Advanced",
    topic: null,
    img: "https://public.bnbstatic.com/static/academy/uploads-original/5705a6aceedd45f1a745542c94506616.png",
  },
  {
    title: "What Is EigenLayer?",
    body: "body",
    url: "https://academy.binance.com/en/articles/what-is-eigenlayer",
    published_date: null,
    reading_time: 6,
    difficulty: "Advanced",
    topic: null,
    img: "https://public.bnbstatic.com/static/academy/uploads-original/d969c1139bec4159af18df62d28fa8f9.jpg",
  },
  {
    title: "What Are Decentralized Derivatives and How Do They Work",
    body: "body",
    url: "https://academy.binance.com/en/articles/what-are-decentralized-derivatives-and-how-do-they-work-in-defi",
    published_date: null,
    reading_time: 6,
    difficulty: "Advanced",
    topic: null,
    img: "https://public.bnbstatic.com/static/academy/uploads-original/696ce5362b16435fb2b43b7400ad1203.png",
  },
  {
    title: "What Are Common Bridge Security Vulnerabilities?",
    body: "body",
    url: "https://academy.binance.com/en/articles/what-are-common-bridge-security-vulnerabilities",
    published_date: null,
    reading_time: 6,
    difficulty: "Advanced",
    topic: null,
    img: "https://public.bnbstatic.com/static/academy/uploads-original/f77235707451429697aebd5261099b95.png",
  },
  {
    title: "What Are the Common Security Issues in GameFi?",
    body: "body",
    url: "https://academy.binance.com/en/articles/what-are-the-common-security-issues-in-gamefi",
    published_date: null,
    reading_time: 6,
    difficulty: "Advanced",
    topic: null,
    img: "https://public.bnbstatic.com/static/academy/uploads-original/93ebfdeaf77e4f4eb3be2050043e7308.png",
  },
  {
    title: "Merkle Trees and Merkle Roots Explained",
    body: "body",
    url: "https://academy.binance.com/en/articles/merkle-trees-and-merkle-roots-explained",
    published_date: null,
    reading_time: '6m',
    difficulty: "Advanced",
    topic: null,
    img: "https://public.bnbstatic.com/static/academy/uploads-original/f105d6c235e3488b8984c5a5e8fcb88f.png",
  },
];

const createMultipleArticles = async (articles) => {
  try {
    await Article.sync({ force: true });

    for (let articleData of articles) {
      await Article.findOrCreate({
        where: { title: articleData.title },
        defaults: {
          topic: articleData.topic,
          title: articleData.title,
          body: articleData.body,
          reading_time: articleData.reading_time,
          difficulty: articleData.difficulty,
          published_at: articleData.published_date,
          article_url: articleData.url,
          img_url: articleData.img,
        },
      });
    }

    console.log("All articles created successfully");
  } catch (err) {
    console.error("Error creating articles:", err.message);
  }
};

createMultipleArticles(articles);
